### PR TITLE
Add linux 386 and armv6 platform support to docker build and publish tasks

### PR DESCRIPTION
**Pull request by richardzone**
Add ARM v6 support so that it can be run on all hardware versions of Raspberry Pi.

Also add 386 support in accordance with [Platform support for Official Images](https://github.com/docker-library/official-images#architectures-other-than-amd64)

### CODE REVIEW

**Review by NN708 — CHANGES_REQUESTED** [review]
Please do not submit these changes into the PR.

**Comment by richardzone** [comment]
@NN708 done

**Comment by NN708** [comment]
@richardzone Did you close this PR intentionally?

**Comment by richardzone** [comment]
@NN708 This won't work with `six8/pyinstaller-alpine` because upstream image was not built these additional platforms.

**Pull request closed without merging**
