### PR TITLE
ip.sb的API更换了，换成最新的API，老的API，403了

### PR DESCRIPTION
**Pull request by Geek-Roc**
老的https://ipv4.ip.sb 403了
换成新的https://api-ipv4.ip.sb/ip
官方API查询地址 https://ip.sb/api/

### CODE REVIEW

**Comment by NewFuture** [comment]
这两个API是模拟CURL请求的，浏览器直接打开会403

```bash
curl http://ipv4.ip.sb
curl http://ipv6.ip.sb
```
文档的说明
>
>Alternatively, for more granularity when querying from a dual-stack environments, the following endpoints are available:
>
> Example (Plain text): https://api.ip.sb/ip (Listen on both IPv4 and IPv6) or curl ip.sb
> Example (Plain text): https://api-ipv4.ip.sb/ip (Listen on IPv4 only) or curl -4 ip.sb or curl ipv4.ip.sb
> Example (Plain text): https://api-ipv6.ip.sb/ip (Listen on IPv6 only) or curl -6 ip.sb or curl ipv6.ip.sb

**Comment by Geek-Roc** [comment]
奇怪的是一直获取不了外网地址，看代码怀疑挂掉了。2.4.4版本。自己更换了API地址就好了，所以以为是更新了API。

**Comment by Geek-Roc** [comment]
> 这两个API是模拟CURL请求的，浏览器直接打开会403
> 
> ```shell
> curl http://ipv4.ip.sb
> curl http://ipv6.ip.sb
> ```
> 
> 文档的说明
> 
> > Alternatively, for more granularity when querying from a dual-stack environments, the following endpoints are available:
> > Example (Plain text): https://api.ip.sb/ip (Listen on both IPv4 and IPv6) or curl ip.sb
> > Example (Plain text): https://api-ipv4.ip.sb/ip (Listen on IPv4 only) or curl -4 ip.sb or curl ipv4.ip.sb
> > Example (Plain text): https://api-ipv6.ip.sb/ip (Listen on IPv6 only) or curl -6 ip.sb or curl ipv6.ip.sb

不过原代码里面写的https://ipv4.ip.sb，现在curl https://ipv4.ip.sb   返回不了IP，需要curl http://ipv4.ip.sb

**Comment by DrawLi** [comment]
今早clone到一台新机也遇到403，临时搭了个网站获取访客ip，修改ip.py中的 # 公网IPV4地址 为自己的才正常工作。

**Comment by Geek-Roc** [comment]
> @Geek-Roc 这个在2.7.1版做了特殊处理(模拟curl)
> 
> https://github.com/NewFuture/DDNS/blob/master/util/ip.py#L53

现在的版本访问的https://ipv4.ip.sb，https现在访问不通了，curl也访问不通。只能访问http://ipv4.ip.sb

**Comment by NewFuture** [comment]
这样的话需要更新一下

**Comment by NewFuture** [comment]
@Geek-Roc 可以reopen一下

**Pull request closed without merging**
